### ISSUE TITLE
Minor typo in page

### ISSUE THREAD

**Issue by SungMatt** [nus-cs2103-AY2324S1/website#3]
https://github.com/nus-cs2103-AY2324S1/website/blob/fcc6687e2d515b949e3c907c5181e56cf8ca6af1/admin/tp-pe-fragment.md?plain=1#L71

It should read `[M48] John Doe` (`M48` is the seat number)
instead of `[M48] John Doe` (`M18` is the seat number)

**Comment by damithc** [comment]
Good catch, @SungMatt Thx. Will fix in the next update.
